# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d11167786d739a0c23e752520458ba1eb41d05a602c717b3e521e11246aab29be6b9f04cd9aca76b7999b0ea3ee8026b2bbeb0c02d7b8a5d29a3ba86f6c34da3

test:
  secret_key_base: c5420e875b98e253518e6a0a96f3b0abaa0c59f7b26e8a528c8deb91ce8571f3eb38b049be5e91c4c373743fa32a2f318603e954e036370ddad3a4355d3334b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
